# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: k3d-dev-registry:5000/backend-server
  tag: v0.1
  pullPolicy: IfNotPresent 
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
  readinessProbe: {}
  # Example (replace readinessProbe: {} with the following):
  # readinessProbe:
  #   httpGet:
  #     path: /ready
  #     port: 3000
  #   initialDelaySeconds: 3
  #   periodSeconds: 5
  livenessProbe: {}
  # Example (replace livenessProbe: {} with the following)::
  # livenessProbe:
  #   httpGet:
  #     path: /live
  #     port: 3000
  #   initialDelaySeconds: 40
  #   periodSeconds: 10  
service:
  name: Node
  type: ClusterIP  # Changed from NodePort to ClusterIP
  servicePort: 3000
  targetPort: 3000  # Ensures service forwards traffic to the correct container port

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
services:
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100
istio:
  enabled: false
  weight: 100
env:
  - name: DB_HOST
    value: mongodb
  - name: DB_USERNAME
    value: root
  - name: DB_PASSWD
    value: "examplepassword"
  - name: DB_NAME
    value: "picsrate_db"
  - name: DB_PORT
    value: "27017"
  - name: PORT
    value: "3000"
  - name: DB_USER
    value: "root"
  - name: DB_PASSWORD
    value: "examplepassword"
