apiVersion: v1
kind: Pod
metadata:
  name: keycloak-utility
spec:
  containers:
  - image: alpine:3.2
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
    volumeMounts:
    - mountPath: /keycloak/data
      name: keycloak-claim
  restartPolicy: Always
  volumes:
  - name: keycloak-claim
    persistentVolumeClaim:
      claimName: pvc-keycloak-themes
