services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ../data/db:/data/db
  # backend:
  #   container_name: backend
  #   depends_on:
  #     - mongodb
  #   image: picsrate-api:v0.1
  #   restart: unless-stopped
  #   env_file: ./.env
  #   ports:
  #     - $PORT:$PORT
  #   environment:
  #     - DB_HOST=mongodb
  #     - DB_USER=$DB_USERNAME
  #     - DB_PASSWORD=$DB_PASSWD
  #     - DB_NAME=$DB_NAME
  #     - DB_PORT=$DB_PORT
  #   stdin_open: true
  #   tty: true
  # keycloak:
  #   image: quay.io/keycloak/keycloak:21.1.1
  #   hostname: keycloak
  #   command: ['start-dev', '--import-realm']
  #   volumes:
  #     - ./keycloak/realm-config:/opt/keycloak/data/import
  #     - ./keycloak/themes/keywind/:/opt/keycloak/themes/keywind/
  #     - ./keycloak/themes/providers/keycloak-webhook-0.5.0-all.jar:/opt/keycloak/providers/
  #   environment:
  #     - KEYCLOAK_LOG_LEVEL=DEBUG
  #     - PROXY_ADDRESS_FORWARDING=true
  #     - KC_PROXY=passthrough
  #     - KEYCLOAK_EXTRA_ARGS="-Dkeycloak.import=/opt/keycloak/data/import"
  #     - KC_DB=dev-file
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #     - KC_FEATURES=scripts
  #     - KC_HTTP_PORT=9080
  #     - KC_HTTPS_PORT=9443
  #     - KEYCLOAK_FRONTEND_URL=http://localhost:9080
  #     - WEBHOOK_HTTP_BASE_PATH=http://host.docker.internal:3000/keycloak-events
  #     - WEBHOOK_HTTP_AUTH_USERNAME=auth_user
  #     - WEBHOOK_HTTP_AUTH_PASSWORD=auth_password
  #     - WEBHOOK_HTTP_INCLUDE_TOKEN=true
  #     - KC_METRICS_ENABLED=true
  #     - KC_LOG_CONSOLE_COLOR=true
  #     - KC_HEALTH_ENABLED=true
  #   # ports:
  #   #   - 9080:9080
  #   #   - 9443:9443
  #   network_mode: "host"

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    hostname: keycloak
    command: ['start-dev --import-realm']
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import
      - ./themes/keywind/:/opt/keycloak/themes/keywind/
      - ./keycloak/themes/providers/keycloak-webhook-0.5.0-all.jar:/opt/keycloak/providers/
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
      - WEBHOOK_HTTP_BASE_PATH=http://host.docker.internal:3000/keycloak-events
      - WEBHOOK_HTTP_AUTH_USERNAME=auth_user
      - WEBHOOK_HTTP_AUTH_PASSWORD=auth_password
      - WEBHOOK_HTTP_INCLUDE_TOKEN=true
      - KC_METRICS_ENABLED=true
      - KC_LOG_CONSOLE_COLOR=true
    ports:
      - 9080:9080
      - 9443:9443
    network_mode: "host"

volumes:
  db:
