services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ../data/db:/data/db
  # backend:
  #   container_name: backend
  #   depends_on:
  #     - mongodb
  #   image: picsrate-api:v0.1
  #   restart: unless-stopped
  #   env_file: ./.env
  #   ports:
  #     - $PORT:$PORT
  #   environment:
  #     - DB_HOST=mongodb
  #     - DB_USER=$DB_USERNAME
  #     - DB_PASSWORD=$DB_PASSWD
  #     - DB_NAME=$DB_NAME
  #     - DB_PORT=$DB_PORT
  #   stdin_open: true
  #   tty: true
  keycloak:
    image: keycloak-webhook-keycloak:latest
    command: ['start-dev','--import-realm']
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import
      - ./keycloak/themes/keywind/:/opt/keycloak/themes/keywind/
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
      - KEYCLOAK_FRONTEND_URL=http://localhost:9080
      - WEBHOOK_HTTP_BASE_PATH=http://host.docker.internal:3000/keycloak-events
      - WEBHOOK_HTTP_AUTH_USERNAME=auth_user
      - WEBHOOK_HTTP_AUTH_PASSWORD=auth_password
      - WEBHOOK_HTTP_INCLUDE_TOKEN=true
      - KC_METRICS_ENABLED=true
      - KC_LOG_CONSOLE_COLOR=true
      - KC_HEALTH_ENABLED=true
    # ports:
    #   - 9080:9080
    #   - 9443:9443
    network_mode: "host"

volumes:
  db: