apiVersion: apps/v1
kind: Deployment
metadata:
  name: picsrate-api
  namespace: studio-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picsrate-api
  template:
    metadata:
      labels:
        app: picsrate-api
    spec:
      containers:
        - name: picsrate-api
          image: studio-registry:5000/picsrate-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mongodb"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWD
              value: "examplepassword"
            - name: DB_NAME
              value : "picsrate_db"
            - name: DB_PORT
              value: "27017"
            - name: PORT
              value: "3000"