apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
  namespace: studio-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
        - name: backend-server
          image: k3d-dev-registry:5000/backend-server:v0.1
          ports:
            - containerPort: 3000