apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: studio-qa
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  
spec:
  rules:
    - host: picsrate-api.bbs-studio.tn
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: picsrate-service
              port:
                number: 80